import { ColorManagementSettings, ColorMatrix, ConversionSettings, CropSettings, CropTab, Curves, ExportOptions, FilmProfile, LightSourceProfile, NotificationSettings, TonalCharacter } from './types';

const DEFAULT_CROP: CropSettings = {
  x: 0,
  y: 0,
  width: 1,
  height: 1,
  aspectRatio: null,
};

const DEFAULT_CURVES: Curves = {
  rgb: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  red: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  green: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  blue: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
};

export const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  format: 'image/jpeg',
  quality: 0.92,
  filenameBase: 'darkslide-converted',
  embedMetadata: true,
  outputProfileId: 'srgb',
  embedOutputProfile: true,
};

export const DEFAULT_COLOR_MANAGEMENT: ColorManagementSettings = {
  inputMode: 'auto',
  inputProfileId: 'srgb',
  outputProfileId: DEFAULT_EXPORT_OPTIONS.outputProfileId,
  embedOutputProfile: DEFAULT_EXPORT_OPTIONS.embedOutputProfile,
};

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  enabled: true,
  exportComplete: true,
  batchComplete: true,
  contactSheetComplete: true,
};

export function createDefaultSettings(overrides: Partial<ConversionSettings> = {}): ConversionSettings {
  return {
    exposure: 0,
    contrast: 10,
    saturation: 100,
    flareCorrection: 50,
    flatFieldEnabled: false,
    temperature: 0,
    tint: 0,
    redBalance: 1,
    greenBalance: 1,
    blueBalance: 1,
    blackPoint: 8,
    whitePoint: 245,
    highlightProtection: 20,
    curves: structuredClone(DEFAULT_CURVES),
    rotation: 0,
    levelAngle: 0,
    crop: structuredClone(DEFAULT_CROP),
    filmBaseSample: null,
    blackAndWhite: {
      enabled: false,
      redMix: 0,
      greenMix: 0,
      blueMix: 0,
      tone: 0,
    },
    sharpen: { enabled: false, radius: 1.0, amount: 50 },
    noiseReduction: { enabled: false, luminanceStrength: 0 },
    ...overrides,
  };
}

export const SUPPORTED_EXTENSIONS = ['.tif', '.tiff', '.png', '.jpg', '.jpeg', '.webp'] as const;
export const RAW_EXTENSIONS = ['.dng', '.cr3', '.nef', '.arw', '.raf', '.rw2'] as const;
export const MAX_IMAGE_PIXELS = 120_000_000;
export const MAX_IMAGE_DIMENSION = 18_000;
export const MAX_FILE_SIZE_BYTES = 500 * 1024 * 1024;
export const MAX_OPEN_TABS = 8;
export const PREVIEW_LEVELS = [512, 1024, 2048, 4096];
export const DIAGNOSTICS_LIMIT = 100;
export const DARKSLIDE_PRESET_FILE_VERSION = '1.0.0';

export interface AspectRatioEntry {
  name: string;
  value: number | null;
  category?: CropTab;
  format?: string;
  gauge?: '35mm' | 'Medium Format';
}

export const ASPECT_RATIOS: AspectRatioEntry[] = [
  { name: 'Free', value: null },
  { name: '2:3', value: 2 / 3, category: 'Film', format: '35mm', gauge: '35mm' },
  { name: '3:2', value: 3 / 2, category: 'Film', format: '35mm', gauge: '35mm' },
  { name: '3:4', value: 3 / 4, category: 'Film', format: 'Half-frame', gauge: '35mm' },
  { name: '4:3', value: 4 / 3, category: 'Film', format: 'Half-frame', gauge: '35mm' },
  { name: '4:5', value: 4 / 5, category: 'Film', format: '6×4.5', gauge: 'Medium Format' },
  { name: '5:4', value: 5 / 4, category: 'Film', format: '6×4.5', gauge: 'Medium Format' },
  { name: '1:1', value: 1, category: 'Film', format: '6×6', gauge: 'Medium Format' },
  { name: '6:7', value: 6 / 7, category: 'Film', format: '6×7', gauge: 'Medium Format' },
  { name: '7:6', value: 7 / 6, category: 'Film', format: '6×7', gauge: 'Medium Format' },
  { name: '2:3', value: 2 / 3, category: 'Film', format: '6×9', gauge: 'Medium Format' },
  { name: '3:2', value: 3 / 2, category: 'Film', format: '6×9', gauge: 'Medium Format' },
  { name: '2:3', value: 2 / 3, category: 'Print' },
  { name: '3:2', value: 3 / 2, category: 'Print' },
  { name: '3:4', value: 3 / 4, category: 'Print' },
  { name: '4:3', value: 4 / 3, category: 'Print' },
  { name: '5:7', value: 5 / 7, category: 'Print' },
  { name: '1:1', value: 1, category: 'Social' },
  { name: '4:5', value: 4 / 5, category: 'Social' },
  { name: '9:16', value: 9 / 16, category: 'Social' },
  { name: '16:9', value: 16 / 9, category: 'Digital' },
];

const IDENTITY_COLOR_MATRIX: ColorMatrix = [
  1, 0, 0,
  0, 1, 0,
  0, 0, 1,
];

const TONAL_CHARACTERS: Record<string, TonalCharacter> = {
  'generic-color': { shadowLift: 0.05, highlightRolloff: 0.5, midtoneAnchor: 0 },
  'portra-400': { shadowLift: 0.15, highlightRolloff: 0.7, midtoneAnchor: 0.01 },
  'portra-160': { shadowLift: 0.12, highlightRolloff: 0.65, midtoneAnchor: 0 },
  'ektar-100': { shadowLift: 0.03, highlightRolloff: 0.3, midtoneAnchor: 0 },
  'gold-200': { shadowLift: 0.08, highlightRolloff: 0.4, midtoneAnchor: 0.02 },
  'fuji-400h': { shadowLift: 0.1, highlightRolloff: 0.55, midtoneAnchor: -0.01 },
  'superia-400': { shadowLift: 0.06, highlightRolloff: 0.4, midtoneAnchor: 0 },
  'cinestill-800t': { shadowLift: 0.12, highlightRolloff: 0.6, midtoneAnchor: 0 },
  'generic-bw': { shadowLift: 0.04, highlightRolloff: 0.5, midtoneAnchor: 0 },
  hp5: { shadowLift: 0.08, highlightRolloff: 0.5, midtoneAnchor: 0 },
  'tri-x': { shadowLift: 0.05, highlightRolloff: 0.35, midtoneAnchor: 0 },
  'delta-3200': { shadowLift: 0.02, highlightRolloff: 0.25, midtoneAnchor: -0.02 },
};

const COLOR_MATRICES: Record<string, ColorMatrix> = {
  'generic-color': IDENTITY_COLOR_MATRIX,
  'portra-400': [1.15, -0.1, -0.05, -0.04, 1.08, -0.04, -0.02, -0.06, 1.08],
  'portra-160': [1.12, -0.08, -0.04, -0.03, 1.06, -0.03, -0.02, -0.05, 1.07],
  'ektar-100': [1.2, -0.12, -0.08, -0.05, 1.1, -0.05, -0.03, -0.08, 1.11],
  'gold-200': [1.18, -0.11, -0.07, -0.05, 1.09, -0.04, -0.03, -0.07, 1.1],
  'fuji-400h': [1.1, -0.06, -0.04, -0.02, 1.05, -0.03, -0.01, -0.04, 1.05],
  'superia-400': [1.12, -0.07, -0.05, -0.03, 1.06, -0.03, -0.02, -0.05, 1.07],
  'cinestill-800t': [1.08, -0.05, -0.03, -0.02, 1.04, -0.02, -0.01, -0.03, 1.04],
};

export const LIGHT_SOURCE_PROFILES: LightSourceProfile[] = [
  { id: 'auto', name: 'Auto (no correction)', colorTemperature: 0, spectralBias: [1, 1, 1], flareCharacteristic: 'medium' },
  { id: 'daylight', name: 'Generic daylight LED panel', colorTemperature: 5500, spectralBias: [1.0, 0.98, 0.95], flareCharacteristic: 'low' },
  { id: 'cs-lite', name: 'CineStill CS-LITE', colorTemperature: 5000, spectralBias: [1.0, 0.95, 0.88], flareCharacteristic: 'low' },
  { id: 'skier', name: 'Skier Sunray Copy Box 3', colorTemperature: 5600, spectralBias: [1.0, 0.97, 0.93], flareCharacteristic: 'low' },
  { id: 'valoi', name: 'VALOI easy35 / Pluto LED', colorTemperature: 5000, spectralBias: [1.0, 0.94, 0.87], flareCharacteristic: 'medium' },
  { id: 'kaiser', name: 'Kaiser Slimlite Plano', colorTemperature: 5300, spectralBias: [1.0, 0.96, 0.91], flareCharacteristic: 'low' },
  { id: 'lomo', name: 'Lomography DigitaLIZA+ LED', colorTemperature: 6000, spectralBias: [0.92, 0.96, 1.0], flareCharacteristic: 'medium' },
  { id: 'tablet', name: 'iPad / tablet backlight', colorTemperature: 6500, spectralBias: [0.88, 0.94, 1.0], flareCharacteristic: 'high' },
];

type BuiltinProfileOptions = Omit<FilmProfile, 'version'>;

function createBuiltinProfile(profile: BuiltinProfileOptions): FilmProfile {
  return {
    version: 1,
    ...profile,
  };
}

export const FILM_PROFILES: FilmProfile[] = [
  createBuiltinProfile({
    id: 'generic-bw',
    name: 'Generic B&W',
    type: 'bw',
    filmType: 'negative',
    category: 'Generic',
    description: 'Neutral black and white inversion with restrained contrast.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 14, highlightProtection: 25 }),
    tonalCharacter: TONAL_CHARACTERS['generic-bw'],
  }),
  createBuiltinProfile({
    id: 'generic-color',
    name: 'Generic Color',
    type: 'color',
    filmType: 'negative',
    category: 'Generic',
    description: 'Balanced color-negative starting point for most consumer scans.',
    defaultSettings: createDefaultSettings({ contrast: 15, redBalance: 1.12, blueBalance: 0.9, highlightProtection: 26 }),
    colorMatrix: COLOR_MATRICES['generic-color'],
    tonalCharacter: TONAL_CHARACTERS['generic-color'],
  }),
  createBuiltinProfile({
    id: 'hp5',
    name: 'Ilford HP5 Plus',
    type: 'bw',
    filmType: 'negative',
    category: 'Ilford',
    description: 'Classic high-speed B&W profile with punchier midtones.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 24, highlightProtection: 30, blackPoint: 12 }),
    tonalCharacter: TONAL_CHARACTERS.hp5,
  }),
  createBuiltinProfile({
    id: 'tri-x',
    name: 'Kodak Tri-X 400',
    type: 'bw',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Distinctive grain and crisp contrast for documentary scans.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 34, highlightProtection: 22, blackPoint: 14 }),
    tonalCharacter: TONAL_CHARACTERS['tri-x'],
  }),
  createBuiltinProfile({
    id: 'delta-3200',
    name: 'Ilford Delta 3200',
    type: 'bw',
    filmType: 'negative',
    category: 'Ilford',
    description: 'Ultra high-speed B&W with dramatic contrast and punchy tones.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 40, highlightProtection: 18, blackPoint: 18, whitePoint: 240 }),
    tonalCharacter: TONAL_CHARACTERS['delta-3200'],
  }),
  createBuiltinProfile({
    id: 'portra-400',
    name: 'Kodak Portra 400',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Warm skin tones with gentle contrast and protected highlights.',
    defaultSettings: createDefaultSettings({ exposure: 4, contrast: 11, saturation: 108, temperature: 4, tint: -2, redBalance: 1.14, blueBalance: 0.88, highlightProtection: 34 }),
    maskTuning: { highlightProtectionBias: 0.08, blackPointBias: -0.02 },
    colorMatrix: COLOR_MATRICES['portra-400'],
    tonalCharacter: TONAL_CHARACTERS['portra-400'],
  }),
  createBuiltinProfile({
    id: 'portra-160',
    name: 'Kodak Portra 160',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Fine-grained portrait stock with neutral, slightly cool rendering.',
    defaultSettings: createDefaultSettings({ exposure: 2, contrast: 8, saturation: 104, temperature: 2, tint: -1, redBalance: 1.10, blueBalance: 0.92, highlightProtection: 30, blackPoint: 6 }),
    maskTuning: { highlightProtectionBias: 0.06, blackPointBias: -0.01 },
    colorMatrix: COLOR_MATRICES['portra-160'],
    tonalCharacter: TONAL_CHARACTERS['portra-160'],
  }),
  createBuiltinProfile({
    id: 'ektar-100',
    name: 'Kodak Ektar 100',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Higher saturation and slightly firmer contrast for vivid negatives.',
    defaultSettings: createDefaultSettings({ contrast: 20, saturation: 130, redBalance: 1.08, blueBalance: 0.92, highlightProtection: 18 }),
    colorMatrix: COLOR_MATRICES['ektar-100'],
    tonalCharacter: TONAL_CHARACTERS['ektar-100'],
  }),
  createBuiltinProfile({
    id: 'gold-200',
    name: 'Kodak Gold 200',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Warm, saturated consumer stock with golden highlights.',
    defaultSettings: createDefaultSettings({ exposure: 6, contrast: 18, saturation: 125, temperature: 8, tint: -2, redBalance: 1.16, blueBalance: 0.86, highlightProtection: 20, blackPoint: 10 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: TONAL_CHARACTERS['gold-200'],
  }),
  createBuiltinProfile({
    id: 'fuji-400h',
    name: 'Fujifilm Pro 400H',
    type: 'color',
    filmType: 'negative',
    category: 'Fuji',
    description: 'Cooler palette with softer contrast and green-friendly balance.',
    defaultSettings: createDefaultSettings({ exposure: 8, contrast: 6, saturation: 96, temperature: -5, tint: 4, greenBalance: 1.08, blueBalance: 1.14, highlightProtection: 30 }),
    colorMatrix: COLOR_MATRICES['fuji-400h'],
    tonalCharacter: TONAL_CHARACTERS['fuji-400h'],
  }),
  createBuiltinProfile({
    id: 'superia-400',
    name: 'Fujifilm Superia 400',
    type: 'color',
    filmType: 'negative',
    category: 'Fuji',
    description: 'Punchy colors with vibrant greens and cool-leaning palette.',
    defaultSettings: createDefaultSettings({ exposure: 4, contrast: 16, saturation: 118, temperature: -3, tint: 3, redBalance: 1.06, greenBalance: 1.06, blueBalance: 0.96, highlightProtection: 22 }),
    colorMatrix: COLOR_MATRICES['superia-400'],
    tonalCharacter: TONAL_CHARACTERS['superia-400'],
  }),
  createBuiltinProfile({
    id: 'cinestill-800t',
    name: 'CineStill 800T',
    type: 'color',
    filmType: 'negative',
    category: 'CineStill',
    description: 'Tungsten-balanced cinema stock with cool shadows and warm highlights.',
    defaultSettings: createDefaultSettings({ exposure: 8, contrast: 12, saturation: 112, temperature: -8, tint: 2, redBalance: 1.18, blueBalance: 1.08, highlightProtection: 35, blackPoint: 6, whitePoint: 240 }),
    maskTuning: { highlightProtectionBias: 0.10, blackPointBias: -0.03 },
    colorMatrix: COLOR_MATRICES['cinestill-800t'],
    tonalCharacter: TONAL_CHARACTERS['cinestill-800t'],
  }),
  createBuiltinProfile({
    id: 'ultramax-400',
    name: 'Kodak UltraMax 400',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Saturated consumer stock with warm daylight rendering.',
    defaultSettings: createDefaultSettings({ exposure: 5, contrast: 17, saturation: 126, temperature: 6, tint: -1, redBalance: 1.14, blueBalance: 0.88, highlightProtection: 22 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: TONAL_CHARACTERS['gold-200'],
  }),
  createBuiltinProfile({
    id: 'colorplus-200',
    name: 'Kodak ColorPlus 200',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Warm budget color negative with easy contrast.',
    defaultSettings: createDefaultSettings({ exposure: 5, contrast: 16, saturation: 118, temperature: 7, tint: -1, redBalance: 1.12, blueBalance: 0.9, highlightProtection: 22 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: TONAL_CHARACTERS['gold-200'],
  }),
  createBuiltinProfile({
    id: 'gold-100',
    name: 'Kodak Gold 100',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Warm low-speed consumer stock with fine grain.',
    defaultSettings: createDefaultSettings({ exposure: 3, contrast: 15, saturation: 120, temperature: 7, tint: -1, redBalance: 1.14, blueBalance: 0.89, highlightProtection: 24, blackPoint: 8 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: TONAL_CHARACTERS['gold-200'],
  }),
  createBuiltinProfile({
    id: 'portra-800',
    name: 'Kodak Portra 800',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Fast portrait stock with soft highlights and lifted shadows.',
    defaultSettings: createDefaultSettings({ exposure: 7, contrast: 9, saturation: 106, temperature: 3, tint: -1, redBalance: 1.13, blueBalance: 0.9, highlightProtection: 36, blackPoint: 7 }),
    maskTuning: { highlightProtectionBias: 0.08, blackPointBias: -0.02 },
    colorMatrix: COLOR_MATRICES['portra-400'],
    tonalCharacter: TONAL_CHARACTERS['portra-400'],
  }),
  createBuiltinProfile({
    id: 'pro-image-100',
    name: 'Kodak Pro Image 100',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Neutral warm pro stock aimed at natural skin tones.',
    defaultSettings: createDefaultSettings({ exposure: 3, contrast: 10, saturation: 104, temperature: 3, tint: -1, redBalance: 1.1, blueBalance: 0.92, highlightProtection: 30, blackPoint: 7 }),
    colorMatrix: COLOR_MATRICES['portra-160'],
    tonalCharacter: TONAL_CHARACTERS['portra-160'],
  }),
  createBuiltinProfile({
    id: 'vision3-250d',
    name: 'Kodak Vision3 250D',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Cinema daylight stock with soft shoulder and broad exposure latitude.',
    defaultSettings: createDefaultSettings({ exposure: 6, contrast: 8, saturation: 98, temperature: 2, tint: -1, redBalance: 1.08, blueBalance: 0.95, highlightProtection: 40, blackPoint: 6 }),
    maskTuning: { highlightProtectionBias: 0.1, blackPointBias: -0.03 },
    colorMatrix: COLOR_MATRICES['portra-160'],
    tonalCharacter: { shadowLift: 0.16, highlightRolloff: 0.78, midtoneAnchor: -0.01 },
  }),
  createBuiltinProfile({
    id: 'vision3-500t',
    name: 'Kodak Vision3 500T',
    type: 'color',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Cinema tungsten stock with cool shadows and a very forgiving shoulder.',
    defaultSettings: createDefaultSettings({ exposure: 8, contrast: 8, saturation: 100, temperature: -6, tint: 1, redBalance: 1.14, blueBalance: 1.02, highlightProtection: 42, blackPoint: 6 }),
    maskTuning: { highlightProtectionBias: 0.12, blackPointBias: -0.03 },
    colorMatrix: COLOR_MATRICES['cinestill-800t'],
    tonalCharacter: { shadowLift: 0.18, highlightRolloff: 0.82, midtoneAnchor: -0.01 },
  }),
  createBuiltinProfile({
    id: 'fuji-c200',
    name: 'Fujifilm C200',
    type: 'color',
    filmType: 'negative',
    category: 'Fuji',
    description: 'Budget Fujifilm stock with lively greens and cooler balance.',
    defaultSettings: createDefaultSettings({ exposure: 4, contrast: 14, saturation: 112, temperature: -2, tint: 2, greenBalance: 1.04, blueBalance: 1.02, highlightProtection: 22 }),
    colorMatrix: COLOR_MATRICES['fuji-400h'],
    tonalCharacter: TONAL_CHARACTERS['fuji-400h'],
  }),
  createBuiltinProfile({
    id: 'superia-xtra-400',
    name: 'Fuji Superia X-TRA 400',
    type: 'color',
    filmType: 'negative',
    category: 'Fuji',
    description: 'Punchy consumer stock with vivid greens and crisp contrast.',
    defaultSettings: createDefaultSettings({ exposure: 4, contrast: 17, saturation: 122, temperature: -3, tint: 3, greenBalance: 1.08, blueBalance: 1.02, highlightProtection: 22 }),
    colorMatrix: COLOR_MATRICES['superia-400'],
    tonalCharacter: TONAL_CHARACTERS['superia-400'],
  }),
  createBuiltinProfile({
    id: 'pro-160ns',
    name: 'Fuji Pro 160NS',
    type: 'color',
    filmType: 'negative',
    category: 'Fuji',
    description: 'Natural-skin portrait stock with soft contrast and cool neutrality.',
    defaultSettings: createDefaultSettings({ exposure: 3, contrast: 7, saturation: 98, temperature: -3, tint: 2, greenBalance: 1.05, blueBalance: 1.06, highlightProtection: 34, blackPoint: 6 }),
    colorMatrix: COLOR_MATRICES['fuji-400h'],
    tonalCharacter: { shadowLift: 0.12, highlightRolloff: 0.68, midtoneAnchor: -0.01 },
  }),
  createBuiltinProfile({
    id: 'cinestill-50d',
    name: 'CineStill 50D',
    type: 'color',
    filmType: 'negative',
    category: 'CineStill',
    description: 'Daylight-balanced cinema-derived stock with clean color and restrained contrast.',
    defaultSettings: createDefaultSettings({ exposure: 3, contrast: 9, saturation: 102, temperature: 1, tint: -1, redBalance: 1.08, blueBalance: 0.96, highlightProtection: 36, blackPoint: 6 }),
    maskTuning: { highlightProtectionBias: 0.1, blackPointBias: -0.02 },
    colorMatrix: COLOR_MATRICES['portra-160'],
    tonalCharacter: { shadowLift: 0.14, highlightRolloff: 0.76, midtoneAnchor: -0.01 },
  }),
  createBuiltinProfile({
    id: 'cinestill-400d',
    name: 'CineStill 400D',
    type: 'color',
    filmType: 'negative',
    category: 'CineStill',
    description: 'Punchier daylight cinema stock with flexible highlights.',
    defaultSettings: createDefaultSettings({ exposure: 5, contrast: 11, saturation: 108, temperature: 1, tint: -1, redBalance: 1.1, blueBalance: 0.96, highlightProtection: 38, blackPoint: 7 }),
    maskTuning: { highlightProtectionBias: 0.1, blackPointBias: -0.02 },
    colorMatrix: COLOR_MATRICES['portra-400'],
    tonalCharacter: { shadowLift: 0.15, highlightRolloff: 0.78, midtoneAnchor: -0.01 },
  }),
  createBuiltinProfile({
    id: 'lomo-400',
    name: 'Lomography CN 400',
    type: 'color',
    filmType: 'negative',
    category: 'Lomography',
    description: 'Saturated, contrasty Lomography color negative with punchy reds.',
    defaultSettings: createDefaultSettings({ exposure: 4, contrast: 20, saturation: 130, temperature: 4, tint: 1, redBalance: 1.12, blueBalance: 0.92, highlightProtection: 18, blackPoint: 10 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: { shadowLift: 0.04, highlightRolloff: 0.35, midtoneAnchor: 0.01 },
  }),
  createBuiltinProfile({
    id: 'lomo-800',
    name: 'Lomography CN 800',
    type: 'color',
    filmType: 'negative',
    category: 'Lomography',
    description: 'High-speed Lomography stock with bold contrast and strong color.',
    defaultSettings: createDefaultSettings({ exposure: 6, contrast: 18, saturation: 128, temperature: 4, tint: 1, redBalance: 1.12, blueBalance: 0.94, highlightProtection: 24, blackPoint: 10 }),
    colorMatrix: COLOR_MATRICES['gold-200'],
    tonalCharacter: { shadowLift: 0.05, highlightRolloff: 0.4, midtoneAnchor: 0.01 },
  }),
  createBuiltinProfile({
    id: 'velvia-50',
    name: 'Fuji Velvia 50',
    type: 'color',
    filmType: 'slide',
    category: 'Fuji',
    description: 'Ultra-saturated slide profile with deep contrast and punchy color.',
    defaultSettings: createDefaultSettings({ exposure: 0, contrast: 22, saturation: 145, temperature: -1, tint: 1, highlightProtection: 10, blackPoint: 8, whitePoint: 248, filmBaseSample: { r: 255, g: 255, b: 255 } }),
    colorMatrix: [1.18, -0.1, -0.08, -0.04, 1.09, -0.03, -0.02, -0.04, 1.14],
    tonalCharacter: { shadowLift: 0.02, highlightRolloff: 0.22, midtoneAnchor: 0.01 },
  }),
  createBuiltinProfile({
    id: 'provia-100f',
    name: 'Fuji Provia 100F',
    type: 'color',
    filmType: 'slide',
    category: 'Fuji',
    description: 'Neutral slide profile with clean color and a restrained shoulder.',
    defaultSettings: createDefaultSettings({ exposure: 0, contrast: 14, saturation: 112, temperature: 0, tint: 0, highlightProtection: 12, blackPoint: 6, whitePoint: 248, filmBaseSample: { r: 255, g: 255, b: 255 } }),
    colorMatrix: [1.08, -0.05, -0.03, -0.02, 1.04, -0.02, -0.01, -0.03, 1.05],
    tonalCharacter: { shadowLift: 0.03, highlightRolloff: 0.28, midtoneAnchor: 0 },
  }),
  createBuiltinProfile({
    id: 'tmax-100',
    name: 'Kodak T-Max 100',
    type: 'bw',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Fine-grain tabular black and white with smooth tonality.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 18, highlightProtection: 28, blackPoint: 10 }),
    tonalCharacter: { shadowLift: 0.06, highlightRolloff: 0.55, midtoneAnchor: 0 },
  }),
  createBuiltinProfile({
    id: 'tmax-400',
    name: 'Kodak T-Max 400',
    type: 'bw',
    filmType: 'negative',
    category: 'Kodak',
    description: 'Versatile tabular black and white with crisp mids.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 24, highlightProtection: 24, blackPoint: 12 }),
    tonalCharacter: { shadowLift: 0.05, highlightRolloff: 0.45, midtoneAnchor: 0 },
  }),
  createBuiltinProfile({
    id: 'fp4',
    name: 'Ilford FP4 Plus',
    type: 'bw',
    filmType: 'negative',
    category: 'Ilford',
    description: 'Classic medium-speed black and white with open shadows.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 18, highlightProtection: 28, blackPoint: 10 }),
    tonalCharacter: { shadowLift: 0.07, highlightRolloff: 0.52, midtoneAnchor: 0 },
  }),
  createBuiltinProfile({
    id: 'panf-50',
    name: 'Ilford Pan F Plus 50',
    type: 'bw',
    filmType: 'negative',
    category: 'Ilford',
    description: 'Ultra-fine grain black and white with strong crispness.',
    defaultSettings: createDefaultSettings({ saturation: 0, contrast: 26, highlightProtection: 22, blackPoint: 12 }),
    tonalCharacter: { shadowLift: 0.04, highlightRolloff: 0.38, midtoneAnchor: 0 },
  }),
];
